// This file is generated by scripts/generate-artworks.mjs. Do not edit it directly.

export type Artwork = {
  id: string;
  name: string;
  price: number; // in INR
  image: string; // path under /public/artworks
  available: boolean; // false = sold
};

export const artworks: Artwork[] = [
  {
    id: "autumn-blossoms",
    name: "Autumn Blossoms",
    price: 1200,
    image: "/artworks/autumn_blossoms-1200-sold.jpeg",
    available: false,
  },
  {
    id: "moon-night",
    name: "Moon Night",
    price: 1800,
    image: "/artworks/moon_night-1800.jpeg",
    available: true,
  },
  {
    id: "red-billed-hornbill",
    name: "Red Billed Hornbill",
    price: 1500,
    image: "/artworks/red_billed_hornbill-1500.jpg",
    available: true,
  },
];
