// This file is generated by scripts/generate-artworks.mjs. Do not edit it directly.

export type Artwork = {
  id: string;
  name: string;
  price: number; // in INR
  image: string; // path under /public/artworks
  available: boolean; // false = sold
};

export const artworks: Artwork[] = [
  {
    id: "autumn",
    name: "Autumn",
    price: 3000,
    image: "/artworks/autumn-3000-sold.jpeg",
    available: false,
  },
  {
    id: "hsgg",
    name: "Hsgg",
    price: 7000,
    image: "/artworks/hsgg-7000-sold.jpg",
    available: false,
  },
  {
    id: "moon",
    name: "Moon",
    price: 2000,
    image: "/artworks/moon-2000.jpeg",
    available: true,
  },
  {
    id: "red-billed-hornbill",
    name: "Red Billed Hornbill",
    price: 1500,
    image: "/artworks/red_billed_hornbill-1500.jpg",
    available: true,
  },
];
